package io.craftgate.model;

public enum BnplCartItemType {

    MOBILE_PHONE_PRICE_ABOVE_REGULATION_LIMIT,
    MOBILE_PHONE_PRICE_BELOW_REGULATION_LIMIT,
    TABLET,
    COMPUTER,
    CONSTRUCTION_MARKET,
    GOLD,
    DIGITAL_PRODUCTS,
    SUPERMARKET,
    WHITE_GOODS,
    WEARABLE_TECHNOLOGY,
    SMALL_HOME_APPLIANCES,
    TV,
    GAMES_CONSOLES,
    AIR_CONDITIONER_AND_HEATER,
    ELECTRONICS,
    ACCESSORIES,
    MOM_AND_BABY_AND_KIDS,
    SHOES,
    CLOTHING,
    COSMETICS_AND_PERSONAL_CARE,
    FURNITURE,
    HOME_LIVING,
    AUTOMOBILE_MOTORCYCLE,
    MOBILE_PHONE_REFURBISHED,
    OTHER
}
